### ISSUE TITLE
Hide upper option

### ISSUE THREAD

**Issue by FayaX-PT** [ggmod/angular-2-data-table#16]
Hello!

How can I remove the 2 buttons options (refresh + select visible columns)?

Thank you

**Comment by FayaX-PT** [comment]
Ok, I already figured it out. 
It can be done with [header]="false" :)

**Comment by MorlaRamakrishna** [comment]
Hi @FayaX-PT ,

I have implemented Demo2 source code in my application, all classes are loading but data table is not visible.  Can you please help me?

Classes are loading like below
![image](https://user-images.githubusercontent.com/26458893/27212479-02ea66f2-527e-11e7-9a52-1261ce8a5360.png)
