### ISSUE TITLE
Angular 4 Data Table Compile issue (/node_modules/angular-4-data-table/src/index.ts) 

### ISSUE THREAD

**Issue by sudha1981** [ggmod/angular-2-data-table#43]
Hello,

iam getting the below error message when i follow the instructions link
https://www.npmjs.com/package/angular-4-data-table-aot

Iam not sure what is wrong simply i have added the module in the app.moudule file.

Note : Used AngularCLI :1.5.2

Any one can suggest how to fix the issue asp.
[Code.zip](https://github.com/ggmod/angular-2-data-table/files/1486198/Code.zip)

Attached code files for your reference.

Error message:
=====================================
ERROR in ./node_modules/angular-4-data-table/src/index.ts
Module build failed: Error: C:\AMD\Examples\Angular4\Grid\Samples\A4DataTable\node_modules\angular-4-data-table\src\index.ts is not part of the compilation output. Please check the other error messages for details.
at AngularCompilerPlugin.getCompiledFile (C:\Examples\Angular4\Grid\Samples\A4DataTable\node_modules@ngtools\webpack\src\angular_compiler_plugin.js:624:23)
at plugin.done.then (C:\Examples\Angular4\Grid\Samples\A4DataTable\node_modules@ngtools\webpack\src\loader.js:467:39)
at 
at process._tickCallback (internal/process/next_tick.js:169:7)
@ ./src/app/app.module.ts 10:0-65
@ ./src/main.ts
@ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by joseph-farruggio** [comment]
Also experiencing this exact issue.

**Comment by sudha1981** [comment]
any one can suggest like "How to fix this issue and struggling from last 2 weeks"

**Comment by parmodmalik** [comment]
any suggestion on above issue.

**Comment by cassildo** [comment]
Same issue here. Any solutions yet?

**Comment by MohamedAbdelkarim** [comment]
Hello guys, you can install angular-4-data-table-fix instead and if you're using Angular 5 cli 1.6.1+ all you have to do is replace ngOutletContext with ngTemplateOutletContext in tabel.template.js in dist folder. that worked perfectly for me. one more thin which drove me crazy if

**Comment by parmodmalik** [comment]
Not working after making above changes,
Below error is still coming
\node_modules\angular-4-data-table\src\index.ts is not part of the compilation output. Please check the other error messages for details.

**Comment by sudha1981** [comment]
[Latest code.zip](https://github.com/ggmod/angular-2-data-table/files/1599736/Latest.code.zip)

The issue fixed with the "MohamedAbdelkarim" comments and attached the working code (app,node_modules) with sample.

I have followed the below steps to fix the Angular 4 Data Table Compile issue 

Step 1: Installed npm angular-4-data-table-fix
              https://www.npmjs.com/package/angular-4-data-table-fix

Step 2: Replace ngOutletContext  with ngTemplateOutletContext  in "node_modules\angular-4-data-table-fix" whole folder

Step 3: Used angular-4-data-table-fix instead of angular-4-data-table.

Oldcode :  import { DataTable, DataTableResource } from 'angular-4-data-table';
New code :  import { DataTable, DataTableResource } from 'angular-4-data-table-fix';

Thank you very much Mohamed for your help.

**Comment by AliAhsanNoon** [comment]
Thank You @sudha1981  , @MohamedAbdelkarim  it worked for me.
